version: "2"
services:
  rancher:
    build: ./web/rancher
    ports:
      - "8080:8080"

# Example of working host code
# sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /Users/james.miller/docker/var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.6 http://10.9.126.211:8080/v1/scripts/E018295D1CF4082B7B23:1483142400000:53rurIg4AdrJNHK0MQF1SFILGE

